CREATE TABLE "Roles"(
	"Id" SERIAL PRIMARY KEY,
	"Name" VARCHAR(100) NOT NULL
);

CREATE TABLE "Users"(
	"Id" SERIAL PRIMARY KEY,
	"Email" VARCHAR(254) NOT NULL UNIQUE,
	"PasswordHash" TEXT NOT NULL,
	"Salt" TEXT NOT NULL,
	"IsEmailConfirmed" BOOLEAN NOT NULL DEFAULT(FALSE),
	"RoleId" INTEGER NOT NULL,
	"ProfileImageUrl" TEXT NULL,
	CONSTRAINT Fk_RolesForUsers
		FOREIGN KEY ("RoleId")
		REFERENCES "Roles"("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens"(
	"Id" SERIAL PRIMARY KEY,
	"Token" TEXT NOT NULL,
	"ExpiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
	"UserId" INTEGER NOT NULL,
	CONSTRAINT Fk_UserForRefreshTokens
		FOREIGN KEY ("UserId")
		REFERENCES "Users"("Id") ON DELETE CASCADE
);
